### ISSUE TITLE
cython=3.0.8 missing from conda-forge

### ISSUE THREAD

**Issue by adrinjalali** [conda-forge/cython-feedstock#134]
### Comment:

https://github.com/conda-forge/cython-feedstock/pull/133 was merged about two weeks ago, but https://anaconda.org/conda-forge/cython/files doesn't include cython=3.0.8. Has it failed to upload?

**Comment by h-vetinari** [comment]
Thanks for the report. It can happen occasionally that the CI of a feedstock isn't triggered upon merge, and this is what happened here (without me noticing). I triggered the build manually now.

**Comment by adrinjalali** [comment]
You're a gem @h-vetinari
