### ISSUE TITLE
win-64 numpy-1.12 compatibility issue

### ISSUE THREAD

**Issue by marscher** [conda-forge/cython-feedstock#19]
Hi,
while trying to update pyemma, I get this error on Appveyor for win-64, np-112:
```
BUILD START: pyemma-2.4-np112py27_0
    (actual version deferred until further download or env creation)
...Can't build C:\projects\pyemma-feedstock\recipe due to unsatisfiable dependencies:
The following specifications were found to be in conflict:
  - cython
  - numpy 1.12*
```
Detailed log:
https://ci.appveyor.com/project/conda-forge/pyemma-feedstock/build/1.0.18/job/qc2llw85tfxuiy19#L148

I've rerendered pyemma's feedstock with smithy 2.3.1. I know, that numpy is not built for this crappy os but should be taken from the defaults channel, somehow it does not happen? Shall I report this to smithy?

Please just close, if so.

**Comment by isuruf** [comment]
This is not a cython issue. `mdtraj` is missing for numpy 1.12. conda-build's conflict messages are wrong sometimes.

> while trying to update pyemma

This didn't happen in updating pyemma. numpy 1.12 was failing in the last commit before the PR as well which was pushed to master without a PR. That's why we recommend to use PRs and to wait till the tests pass to merge.

**Comment by marscher** [comment]
On 05/21/2017 02:43 AM, Isuru Fernando wrote:
> This is not a cython issue. |mdtraj| is missing for numpy 1.12. conda-build's conflict messages are wrong sometimes.
> 
>     while trying to update pyemma
> 
> This didn't happen in updating pyemma. numpy 1.12 was failing in the last commit before the PR as well which was pushed to master without a PR. That's why we
> recommend to use PRs and to wait till the tests pass to merge.
Thanks for pointing this out. Which commands did you use to figure this out? I assume you are using windows?

**Comment by isuruf** [comment]
I'm using Linux. What I did was I looked at the build requirements,
```
  build:
    - cython
    - mdtraj >=1.8
    - numpy x.x
    - python
    - setuptools
```
I know that Cython doesn't need numpy, so I checked mdtraj here, https://anaconda.org/conda-forge/mdtraj/files. Looking at the list there were no `np112` packages for windows.

**Comment by marscher** [comment]
Thank you again. I think I've once requested a descriptive exception in conda-build and it is on the wish list now (but has a low priority).

**Comment by jakirkham** [comment]
Do you have a link for the issue, @marscher?

**Comment by marscher** [comment]
https://github.com/conda/conda/issues/4671
