### ISSUE TITLE
SystemError or Compiler crash or errors in Code.py

### ISSUE THREAD

**Issue by cdeil** [conda-forge/cython-feedstock#28]
Dear maintainers of Cython on conda-forge.

We have an issue with Cython crashing, that so far has been only seen with the latest Cython 0.27.3 from conda-forge.

I initially filed over at https://github.com/cython/cython/issues/2104, all the infos are there, including four lines you can copy & paste that should let you reproduce the crash. @jakirkham suggested I open an issue here as well. It's currently unclear if the issue is with Cython itself or with the Cython packaged here in conda-forge.

**Comment by jakirkham** [comment]
Based on [this test with `pip`]( https://github.com/cython/cython/issues/2104#issuecomment-366535457 ), sounds like it is not a packaging issue on our end. That said, we can keep the issue open in case there is a patch we can apply to workaround the problem.

**Comment by cdeil** [comment]
I'm closing this issue now.

If you read through https://github.com/cython/cython/issues/2104 you'll see that this is a Cython and/or setuptools issue, that also appears independently  of conda.

@jakirkham - Sorry for the noise, and thank you for your help, and maintaining the Cython conda package!
