### ISSUE TITLE
This package should depend on the C compiler its Python was build with.

### ISSUE THREAD

**Issue by cjw296** [conda-forge/cython-feedstock#76]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

This package should depend on `gcc_linux-64` such that it uses the same C compiler that the Python binary was built with.
With this, it falls back to whatever C compiler is lying around on the path, which in the case of RHEL7 is a pretty ancient version of `gcc`.

https://github.com/AnacondaRecipes/cython-feedstock/issues/2 for matching issue for the Anaconda distribution.

**Comment by jakirkham** [comment]
Not sure that is a good idea as we need recipes to specifically list the compilers they depend on to ensure they get installed and their runtime libraries are added via `run_exports` to things they build

For local usage, one can install [the `compilers` package]( https://github.com/conda-forge/compilers-feedstock/ ) or pick out specific compilers like [the `c-compiler`]( https://github.com/conda-forge/compilers-feedstock/blob/86145563bb81f82a29dab05810326ae68c907cb0/recipe/meta.yaml#L35 )

**Comment by cjw296** [comment]
I didn't know about the `compilers` package, and that may be a good choice.
Why not have the `cython` package have a runtime dependency on it?

Unless I'm missing something, `cython` is unusable without a C compiler, and relying on the operating system's one is likely to run into incompatibilities.

That said, the specific issue I hit would have still occurred had the compiler provided by the `compilers` metapackage not matched the one Python was built with.

I'm not sure if conda has a way to express this dependency? I do feel cython does have a fairly hard dependency on "whatever C compiler was used to build the python binary/libpython currently available in the conda environment"...

**Comment by jakirkham** [comment]
Already answered above. Put another way it's going to cause serious problems building other packages in conda-forge that depend on `cython`. So it doesn't sound feasible

`cython` already will have a dependency on the C compiler's runtime libraries. One can maybe use that to more carefully pick the version

That said, it would be good to see first whether using the `compilers` package works or not (sounds like this hasn't been tried yet?). Please give that a try and let us know how it goes :)

**Comment by rgommers** [comment]
I agree with `jakirkham`, this is not a good idea. An installed `cython` package can work with many compilers, including system compilers.

There is nothing to do here, I propose to close this issue.

**Comment by rgommers** [comment]
Also keep in mind that `cython` fundamentally is a _transpiler_, it can emit C/C++ code and stop there. That is how SciPy uses it for example. So Cython itself has no dependency on any compiler.
